services:
  renner-family-photos:
    build:
      context: "."
      dockerfile: "./.docker/dockerfile"
    ports:
      - "5000:5000"
    volumes:
      - ./.secrets/:/app/.secrets/
      - ./database/:/app/database/
    environment:
      - ./.secrets/variables.env
