FROM node:16.11.1-alpine3.14

WORKDIR /app

COPY ./package.json ./
RUN npm i
RUN npm install -g serve

COPY ./public ./public
COPY ./src ./src

RUN npm run build
RUN rm -fr ./public ./src

EXPOSE 3000

CMD [ "serve", "build"]