BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "reset_hashes" (
	"id"	INTEGER NOT NULL UNIQUE,
	"hash"	TEXT NOT NULL UNIQUE,
	"expiration_time"	TEXT NOT NULL,
	"user_id"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("user_id") REFERENCES "users"("id")
);
CREATE TABLE IF NOT EXISTS "captions" (
	"id"	INTEGER NOT NULL UNIQUE,
	"text"	TEXT,
	"date"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER NOT NULL UNIQUE,
	"email"	TEXT NOT NULL UNIQUE COLLATE NOCASE,
	"password_hash"	TEXT NOT NULL DEFAULT ' ',
	"admin"	INTEGER,
	"active"	INTEGER DEFAULT 1,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
