FROM python:3-alpine

RUN apk add --no-cache nodejs npm build-base

WORKDIR /app

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

RUN mkdir client client/public client/src
COPY ./client/package.json ./client/
COPY ./client/public/ ./client/public/
COPY ./client/src/ ./client/src/
RUN cd client && ls && npm i --no-cache && npm run build && cd ..
RUN rm -fr ./client/src/ ./client/public/

COPY ./app.py ./google_api.py ./config.py ./utilities.py ./
COPY ./database/db.py ./database/schema.sql ./database/
RUN mkdir ./database/logs

EXPOSE 5000

CMD [ "gunicorn", "-b 0.0.0.0:5000", "-w 2", "app:app"]